[colors.primary]
background = '#131313'
foreground = '#e2e2e2'

[colors.cursor]
text = '#131313'
cursor = '#e2e2e2'

[colors.vi_mode_cursor]
text = '#131313'
cursor = '#9bd67f'

[colors.search.matches]
foreground = '#474747'
background = '#a0cfd0'

[colors.search.focused_match]
foreground = '#474747'
background = '#9bd67f'

[colors.footer_bar]
foreground = '#474747'
background = '#e2e2e2'

[colors.hints.start]
foreground = '#474747'
background = '#bccbb0'

[colors.hints.end]
foreground = '#474747'
background = '#bccbb0'

[colors.selection]
text = '#c6c6c6'
background = '#474747'


[colors.normal]
black   = '#474747'
red     = '#ffb4ab'
green   = '#9bd67f'
yellow  = '#bccbb0'
blue    = '#a0cfd0'
magenta = '#9bd67f'
cyan    = '#bccbb0'
white   = '#e2e2e2'


[colors.bright]
black   = '#919191'
red     = '#ffb4ab'
green   = '#9bd67f'
yellow  = '#bccbb0'
blue    = '#a0cfd0'
magenta = '#9bd67f'
cyan    = '#bccbb0'
white   = '#e2e2e2'


[colors.dim]
black   = '#474747'
red     = '#ffb4ab'
green   = '#9bd67f'
yellow  = '#bccbb0'
blue    = '#a0cfd0'
magenta = '#9bd67f'
cyan    = '#bccbb0'
white   = '#e2e2e2'
