cursor #e4e3da
cursor_text_color #c6c8b7

foreground            #e4e3da
background            #13140f
selection_foreground  #2c331a
selection_background  #c2caa6
url_color             #bbcf83

color0   #13140f
color1   #ee7e6b
color2   #70cf67
color3   #ffea72
color4   #adc46e
color5   #4e5f1f
color6   #bbcf83
color7   #d5d9cc
color8   #83867c
color9   #ffad9f
color10  #a9f8a1
color11  #fff2a5
color12  #d1e39c
color13  #edffbd
color14  #f3ffd4
color15  #fdfff8
