cursor #1b1c17
cursor_text_color #45483c

foreground            #1b1c17
background            #fbfaf0
selection_foreground  #ffffff
selection_background  #c2caa6
url_color             #546526

color0   #13140f
color1   #792c1e
color2   #195f12
color3   #998409
color4   #576a24
color5   #a9b28f
color6   #546526
color7   #232321
color8   #6b6c68
color9   #ab5747
color10  #348c2c
color11  #a59115
color12  #617727
color13  #a9b28f
color14  #78835a
color15  #bebfba
