[colors.primary]
background = '#fbfaf0'
foreground = '#1b1c17'

[colors.selection]
text = '#1b1c17'
background = '#8b9e58'

[colors.cursor]
text = '#fbfaf0'
cursor = '#546526'

[colors.normal]
black   = '#13140f'
red     = '#792c1e'
green   = '#195f12'
yellow  = '#998409'
blue    = '#576a24'
magenta = '#a9b28f'
cyan    = '#546526'
white   = '#232321'

[colors.bright]
black   = '#6b6c68'
red     = '#ab5747'
green   = '#348c2c'
yellow  = '#a59115'
blue    = '#617727'
magenta = '#a9b28f'
cyan    = '#78835a'
white   = '#bebfba'
