[colors.primary]
background = '#13140f'
foreground = '#e4e3da'

[colors.selection]
text = '#e4e3da'
background = '#8b9e58'

[colors.cursor]
text = '#13140f'
cursor = '#bbcf83'

[colors.normal]
black   = '#13140f'
red     = '#ee7e6b'
green   = '#70cf67'
yellow  = '#ffea72'
blue    = '#adc46e'
magenta = '#4e5f1f'
cyan    = '#bbcf83'
white   = '#d5d9cc'

[colors.bright]
black   = '#83867c'
red     = '#ffad9f'
green   = '#a9f8a1'
yellow  = '#fff2a5'
blue    = '#d1e39c'
magenta = '#edffbd'
cyan    = '#f3ffd4'
white   = '#fdfff8'
